package com.emitrom.ti4j.mobile.client.core.events;

import com.emitrom.ti4j.core.client.JsoHelper;
import com.emitrom.ti4j.core.client.ProxyObject;
import com.google.gwt.core.client.JavaScriptObject;

/**
 * Class used in any event or callback which needs to report a success or
 * failure.
 * 
 */
public class ErrorResponse extends ProxyObject {

    protected ErrorResponse(JavaScriptObject obj) {
        jsObj = obj;
    }

    /**
     * Error code. Returns 0 if success is true.
     * <p>
     * Error code will be 0 if success is true, nonzero otherwise. If the error
     * was generated by the operating system, that system's error value is used.
     * Otherwise, this value will be -1.
     */
    public int getCode() {
        return JsoHelper.getAttributeAsInt(jsObj, "code");
    }

    /**
     * Error message, if any returned.
     * <p>
     * Will be undefined if success is true.
     */
    public String getError() {
        return JsoHelper.getAttribute(jsObj, "error");
    }

    /**
     * Indicates if the operation succeeded.
     * <p>
     * Returns true if request succeeded, false otherwise.
     */
    public boolean isSuccess() {
        return JsoHelper.getAttributeAsBoolean(jsObj, "success");
    }
}
